-- 1) Create products table used by shop + recommended sections
create table if not exists public.products (
    id bigint generated by default as identity primary key,
    name text not null,
    description text,
    category text not null,
    category_label text,
    product_group text,
    product_type text,
    price numeric(10,2) not null default 0,
    old_price numeric(10,2),
    rating numeric(2,1) not null default 0,
    reviews integer not null default 0,
    image_url text,
    image text,
    tag text,
    created_at timestamptz not null default now()
);

alter table public.products
    add column if not exists product_group text,
    add column if not exists product_type text;

create index if not exists idx_products_category on public.products (category);
create index if not exists idx_products_rating on public.products (rating desc);
create index if not exists idx_products_created_at on public.products (created_at desc);

alter table public.products enable row level security;

drop policy if exists "Public can read products" on public.products;

create policy "Public can read products"
on public.products
for select
to anon, authenticated
using (true);

with base as (
    select
        gs as seq,
        (array['Aurora', 'Velvet', 'Golden', 'Midnight', 'Cedar', 'Maple', 'Cocoa', 'Amber', 'Summit', 'Noble'])[((gs - 1) % 10) + 1] as adjective,
        (array['Blend', 'Reserve', 'Craft', 'Estate', 'Roast', 'Series', 'Collection', 'Batch', 'Select', 'Signature'])[(((gs - 1) / 10) % 10) + 1] as series,
        (array['espresso', 'latte', 'cold-brew', 'beans', 'equipment', 'pastry'])[((gs - 1) % 6) + 1] as category,
        (array['House', 'Seasonal', 'Single Origin', 'Specialty', 'Cafe Essentials'])[((gs - 1) % 5) + 1] as product_group,
        (array['popular', 'new', 'sale', null, null])[((gs - 1) % 5) + 1] as tag
    from generate_series(1, 100) as gs
),
generated_products as (
    select
        format('%s %s %s', adjective, series, lpad(seq::text, 3, '0')) as name,
        format('A curated %s coffee product from our %s lineup, crafted for consistent flavor and aroma.', category, product_group) as description,
        category,
        case category
            when 'espresso' then 'Espresso'
            when 'latte' then 'Latte'
            when 'cold-brew' then 'Cold Brew'
            when 'beans' then 'Coffee Beans'
            when 'equipment' then 'Equipment'
            else 'Pastry'
        end as category_label,
        product_group,
        case category
            when 'espresso' then (array['Single Shot', 'Double Shot', 'Ristretto', 'Lungo'])[((seq - 1) % 4) + 1]
            when 'latte' then (array['Classic Latte', 'Flavored Latte', 'Iced Latte', 'Oat Latte'])[((seq - 1) % 4) + 1]
            when 'cold-brew' then (array['Classic Cold Brew', 'Nitro', 'Vanilla Infused', 'Barrel Aged'])[((seq - 1) % 4) + 1]
            when 'beans' then (array['Light Roast', 'Medium Roast', 'Dark Roast', 'Espresso Roast'])[((seq - 1) % 4) + 1]
            when 'equipment' then (array['Brewer', 'Grinder', 'Scale', 'Kettle'])[((seq - 1) % 4) + 1]
            else (array['Croissant', 'Muffin', 'Cookie', 'Cake'])[((seq - 1) % 4) + 1]
        end as product_type,
        case category
            when 'espresso' then round((3.20 + (seq % 18) * 0.15)::numeric, 2)
            when 'latte' then round((4.50 + (seq % 20) * 0.18)::numeric, 2)
            when 'cold-brew' then round((4.80 + (seq % 16) * 0.22)::numeric, 2)
            when 'beans' then round((10.00 + (seq % 25) * 0.75)::numeric, 2)
            when 'equipment' then round((18.00 + (seq % 35) * 1.35)::numeric, 2)
            else round((2.20 + (seq % 12) * 0.35)::numeric, 2)
        end as price,
        case
            when seq % 4 = 0 then round((
                case category
                    when 'espresso' then 3.20 + (seq % 18) * 0.15
                    when 'latte' then 4.50 + (seq % 20) * 0.18
                    when 'cold-brew' then 4.80 + (seq % 16) * 0.22
                    when 'beans' then 10.00 + (seq % 25) * 0.75
                    when 'equipment' then 18.00 + (seq % 35) * 1.35
                    else 2.20 + (seq % 12) * 0.35
                end
            ) * 1.15::numeric, 2)
            else null
        end as old_price,
        round((3.8 + (seq % 12) * 0.1)::numeric, 1) as rating,
        20 + ((seq * 7) % 320) as reviews,
        tag
    from base
)
insert into public.products
(name, description, category, category_label, product_group, product_type, price, old_price, rating, reviews, tag)
select
    gp.name,
    gp.description,
    gp.category,
    gp.category_label,
    gp.product_group,
    gp.product_type,
    gp.price,
    gp.old_price,
    gp.rating,
    gp.reviews,
    gp.tag
from generated_products gp
where not exists (
    select 1
    from public.products p
    where p.name = gp.name
);
